version: '3.8'

services:
  cluster-state-api:
    build: ./cluster-state-api
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - DB_CONNECTION=pg
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    depends_on:
      - db

  cluster-state-dashboard:
    build: ./cluster-state-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://cluster-state-api:3333/api/v1 # Updated API_BASE_URL

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
